global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
