server:
  port: 8082
spring:
  application:
    name: payment-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
tracing:
  sampling:
    probability: 1.0
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans
